export default class PassiveStatRulesRecord {
    static FIELD_statRulesId = "statRulesId";
    static FIELD_addSvDmgVsFvNpcId = "addSvDmgVsFvNpcId";
    static FIELD_addSvDmgToFvSkillId = "addSvDmgToFvSkillId";
    static FIELD_chgSidearmDmgBySvPercent = "chgSidearmDmgBySvPercent";
    static FIELD_chgResistanceByFvPercentOfSv = "chgResistanceByFvPercentOfSv";
    static FIELD_chgDefenseByFvPercentOfSv = "chgDefenseByFvPercentOfSv";
    static FIELD_chgDefenseVsNpcId = "chgDefenseVsNpcId";
    static FIELD_chgDefenseVsNpcIdByFv = "chgDefenseVsNpcIdByFv";
    static FIELD_chgStrengthBySv = "chgStrengthBySv";
    static FIELD_chgDexterityBySv = "chgDexterityBySv";
    static FIELD_chgTechnologyBySv = "chgTechnologyBySv";
    static FIELD_chgSupportBySv = "chgSupportBySv";
    static FIELD_chgSupportBySvPercent = "chgSupportBySvPercent";
    static FIELD_chgSupportBySvPercentOfTargetSupport = "chgSupportBySvPercentOfTargetSupport";
    static FIELD_chgHighStatBySvPercent = "chgHighStatBySvPercent";
    static FIELD_chgCurrentDefenseBySvPercent = "chgCurrentDefenseBySvPercent";
    static FIELD_chgCurrentResistancebySvPercent = "chgCurrentResistanceBySvPercent";
    static FIELD_chgStrengthByFv = "chgStrengthByFv";
    static FIELD_chgDexterityByFv = "chgDexterityByFv";
    static FIELD_chgTechnologyByFv = "chgTechnologyByFv";
    static FIELD_chgSupportByFv = "chgSupportByFv";
    static FIELD_chgDefensesByLvlOverDuration = "chgDefensesByLvlOverDuration";
    static FIELD_chgDefenseByFvPercent = "chgDefenseByFvPercent";
    static FIELD_chgResistByFvPercent = "chgResistByFvPercent";
    static FIELD_addAllStatsByFvPercent = "addAllStatsByFvPercent";
    static FIELD_chgAuxDmgBySvPercent = "chgAuxDmgBySvPercent";
    static FIELD_chgStrengthBySvPercent = "chgStrengthBySvPercent";
    static FIELD_chgDexterityBySvPercent = "chgDexterityBySvPercent";
    static FIELD_chgTechnologyBySvPercent = "chgTechnologyBySvPercent";
    static FIELD_addSvDmgToFvSkillId2 = "addSvDmgToFvSkillId2";
    static FIELD_chgPriDmgBySvPercent = "chgPriDmgBySvPercent";
    static FIELD_chgLowDefBySvPercent = "chgLowDefBySvPercent";
    static FIELD_chgStrengthByFvPercent = "chgStrengthByFvPercent";
    static FIELD_chgDexterityByFvPercent = "chgDexterityByFvPercent";
    static FIELD_chgTechnologyByFvPercent = "chgTechnologyByFvPercent";
    static FIELD_chgSupportByFvPercent = "chgSupportByFvPercent";
    static FIELD_chgHighStatByFvPercent = "chgHighStatByFvPercent";
    static FIELD_chgDefenseByFvPercent2 = "chgDefenseByFvPercent2";
    static FIELD_chgResistByFvPercent2 = "chgResistByFvPercent2";
    static FIELD_chgHighStatByFv = "chgHighStatByFv";
    static FIELD_chgHighStatBySv = "chgHighStatBySv";
    static FIELD_chgBotDmgBySvPercent = "chgBotDmgBySvPercent";
    static FIELD_reducePriDmgBySvPercent = "reducePriDmgBySvPercent";
    static FIELD_reduceSidearmDmgBySvPercent = "reduceSidearmDmgBySvPercent";
    static FIELD_reduceAuxDmgBySvPercent = "reduceAuxDmgBySvPercent";
    
    static templates  = [PassiveStatRulesRecord.FIELD_statRulesId,PassiveStatRulesRecord.FIELD_addSvDmgVsFvNpcId,PassiveStatRulesRecord.FIELD_addSvDmgToFvSkillId,PassiveStatRulesRecord.FIELD_chgSidearmDmgBySvPercent,PassiveStatRulesRecord.FIELD_chgResistanceByFvPercentOfSv,PassiveStatRulesRecord.FIELD_chgDefenseByFvPercentOfSv,PassiveStatRulesRecord.FIELD_chgDefenseVsNpcId,PassiveStatRulesRecord.FIELD_chgDefenseVsNpcIdByFv,PassiveStatRulesRecord.FIELD_chgStrengthBySv,PassiveStatRulesRecord.FIELD_chgDexterityBySv,PassiveStatRulesRecord.FIELD_chgTechnologyBySv,PassiveStatRulesRecord.FIELD_chgSupportBySv,PassiveStatRulesRecord.FIELD_chgSupportBySvPercent,PassiveStatRulesRecord.FIELD_chgSupportBySvPercentOfTargetSupport,PassiveStatRulesRecord.FIELD_chgHighStatBySvPercent,PassiveStatRulesRecord.FIELD_chgCurrentDefenseBySvPercent,PassiveStatRulesRecord.FIELD_chgCurrentResistancebySvPercent,PassiveStatRulesRecord.FIELD_chgStrengthByFv,PassiveStatRulesRecord.FIELD_chgDexterityByFv,PassiveStatRulesRecord.FIELD_chgTechnologyByFv,PassiveStatRulesRecord.FIELD_chgSupportByFv,PassiveStatRulesRecord.FIELD_chgDefensesByLvlOverDuration,PassiveStatRulesRecord.FIELD_chgDefenseByFvPercent,PassiveStatRulesRecord.FIELD_chgResistByFvPercent,PassiveStatRulesRecord.FIELD_addAllStatsByFvPercent,PassiveStatRulesRecord.FIELD_chgAuxDmgBySvPercent,PassiveStatRulesRecord.FIELD_chgStrengthBySvPercent,PassiveStatRulesRecord.FIELD_chgDexterityBySvPercent,PassiveStatRulesRecord.FIELD_chgTechnologyBySvPercent,PassiveStatRulesRecord.FIELD_addSvDmgToFvSkillId2,PassiveStatRulesRecord.FIELD_chgPriDmgBySvPercent,PassiveStatRulesRecord.FIELD_chgLowDefBySvPercent,PassiveStatRulesRecord.FIELD_chgStrengthByFvPercent,PassiveStatRulesRecord.FIELD_chgDexterityByFvPercent,PassiveStatRulesRecord.FIELD_chgTechnologyByFvPercent,PassiveStatRulesRecord.FIELD_chgSupportByFvPercent,PassiveStatRulesRecord.FIELD_chgHighStatByFvPercent,PassiveStatRulesRecord.FIELD_chgDefenseByFvPercent2,PassiveStatRulesRecord.FIELD_chgResistByFvPercent2,PassiveStatRulesRecord.FIELD_chgHighStatByFv,PassiveStatRulesRecord.FIELD_chgHighStatBySv,PassiveStatRulesRecord.FIELD_chgBotDmgBySvPercent,PassiveStatRulesRecord.FIELD_reducePriDmgBySvPercent,PassiveStatRulesRecord.FIELD_reduceSidearmDmgBySvPercent,PassiveStatRulesRecord.FIELD_reduceAuxDmgBySvPercent];

    statRulesId: number;
    addSvDmgVsFvNpcId: number;
    addSvDmgToFvSkillId: number;
    chgSidearmDmgBySvPercent: boolean;
    chgResistanceByFvPercentOfSv: number;
    chgDefenseByFvPercentOfSv: number;
    chgDefenseVsNpcId: number;
    chgDefenseVsNpcIdByFv: number;
    chgStrengthBySv: boolean;
    chgDexterityBySv: boolean;
    chgTechnologyBySv: boolean;
    chgSupportBySv: boolean;
    chgSupportBySvPercent: boolean;
    chgSupportBySvPercentOfTargetSupport: boolean;
    chgHighStatBySvPercent: boolean;
    chgCurrentDefenseBySvPercent: boolean;
    chgCurrentResistancebySvPercent: boolean;
    chgStrengthByFv: number;
    chgDexterityByFv: number;
    chgTechnologyByFv: number;
    chgSupportByFv: number;
    chgDefensesByLvlOverDuration: number;
    chgDefenseByFvPercent: number;
    chgResistByFvPercent: number;
    addAllStatsByFvPercent: number;
    chgAuxDmgBySvPercent: boolean;
    chgStrengthBySvPercent: boolean;
    chgDexterityBySvPercent: boolean;
    chgTechnologyBySvPercent: boolean;
    addSvDmgToFvSkillId2: number;
    chgPriDmgBySvPercent: boolean;
    chgLowDefBySvPercent: boolean;
    chgStrengthByFvPercent: number;
    chgDexterityByFvPercent: number;
    chgTechnologyByFvPercent: number;
    chgSupportByFvPercent: number;
    chgHighStatByFvPercent: number;
    chgDefenseByFvPercent2: number;
    chgResistByFvPercent2: number;
    chgHighStatByFv: number;
    chgHighStatBySv: boolean;
    chgBotDmgBySvPercent: boolean;
    reducePriDmgBySvPercent: boolean;
    reduceSidearmDmgBySvPercent: boolean;
    reduceAuxDmgBySvPercent: boolean;

    constructor(obj: any) {
        this.statRulesId = parseInt(obj["statRulesId"]);
        this.addSvDmgVsFvNpcId = parseInt(obj["addSvDmgVsFvNpcId"]);
        this.addSvDmgToFvSkillId = parseInt(obj["addSvDmgToFvSkillId"]);
        this.chgSidearmDmgBySvPercent = Boolean(parseInt(obj["chgSidearmDmgBySvPercent"]));
        this.chgResistanceByFvPercentOfSv = parseInt(obj["chgResistanceByFvPercentOfSv"]);
        this.chgDefenseByFvPercentOfSv = parseInt(obj["chgDefenseByFvPercentOfSv"]);
        this.chgDefenseVsNpcId = parseInt(obj["chgDefenseVsNpcId"]);
        this.chgDefenseVsNpcIdByFv = parseInt(obj["chgDefenseVsNpcIdByFv"]);
        this.chgStrengthBySv = Boolean(parseInt(obj["chgStrengthBySv"]));
        this.chgDexterityBySv = Boolean(parseInt(obj["chgDexterityBySv"]));
        this.chgTechnologyBySv = Boolean(parseInt(obj["chgTechnologyBySv"]));
        this.chgSupportBySv = Boolean(parseInt(obj["chgSupportBySv"]));
        this.chgSupportBySvPercent = Boolean(parseInt(obj["chgSupportBySvPercent"]));
        this.chgSupportBySvPercentOfTargetSupport = Boolean(parseInt(obj["chgSupportBySvPercentOfTargetSupport"]));
        this.chgHighStatBySvPercent = Boolean(parseInt(obj["chgHighStatBySvPercent"]));
        this.chgCurrentDefenseBySvPercent = Boolean(parseInt(obj["chgCurrentDefenseBySvPercent"]));
        this.chgCurrentResistancebySvPercent = Boolean(parseInt(obj["chgCurrentResistancebySvPercent"]));
        this.chgStrengthByFv = parseInt(obj["chgStrengthByFv"]);
        this.chgDexterityByFv = parseInt(obj["chgDexterityByFv"]);
        this.chgTechnologyByFv = parseInt(obj["chgTechnologyByFv"]);
        this.chgSupportByFv = parseInt(obj["chgSupportByFv"]);
        this.chgDefensesByLvlOverDuration = Number(obj["chgDefensesByLvlOverDuration"]);
        this.chgDefenseByFvPercent = Number(obj["chgDefenseByFvPercent"]);
        this.chgResistByFvPercent = Number(obj["chgResistByFvPercent"]);
        this.addAllStatsByFvPercent = Number(obj["addAllStatsByFvPercent"]);
        this.chgAuxDmgBySvPercent = Boolean(parseInt(obj["chgAuxDmgBySvPercent"]));
        this.chgStrengthBySvPercent = Boolean(parseInt(obj["chgStrengthBySvPercent"]));
        this.chgDexterityBySvPercent = Boolean(parseInt(obj["chgDexterityBySvPercent"]));
        this.chgTechnologyBySvPercent = Boolean(parseInt(obj["chgTechnologyBySvPercent"]));
        this.addSvDmgToFvSkillId2 = parseInt(obj["addSvDmgToFvSkillId2"]);
        this.chgPriDmgBySvPercent = Boolean(parseInt(obj["chgPriDmgBySvPercent"]));
        this.chgLowDefBySvPercent = Boolean(parseInt(obj["chgLowDefBySvPercent"]));
        this.chgStrengthByFvPercent = parseInt(obj["chgStrengthByFvPercent"]);
        this.chgDexterityByFvPercent = parseInt(obj["chgDexterityByFvPercent"]);
        this.chgTechnologyByFvPercent = parseInt(obj["chgTechnologyByFvPercent"]);
        this.chgSupportByFvPercent = parseInt(obj["chgSupportByFvPercent"]);
        this.chgHighStatByFvPercent = parseInt(obj["chgHighStatByFvPercent"]);
        this.chgDefenseByFvPercent2 = Number(obj["chgDefenseByFvPercent2"]);
        this.chgResistByFvPercent2 = Number(obj["chgResistByFvPercent2"]);
        this.chgHighStatByFv = parseInt(obj["chgHighStatByFv"]);
        this.chgHighStatBySv = Boolean(parseInt(obj["chgHighStatBySv"]));
        this.chgBotDmgBySvPercent = Boolean(parseInt(obj["chgBotDmgBySvPercent"]));
        this.reducePriDmgBySvPercent = Boolean(parseInt(obj["reducePriDmgBySvPercent"]));
        this.reduceSidearmDmgBySvPercent = Boolean(parseInt(obj["reduceSidearmDmgBySvPercent"]));
        this.reduceAuxDmgBySvPercent = Boolean(parseInt(obj["reduceAuxDmgBySvPercent"]));
    }
}